#!/var/ossec/framework/python/bin/python3
# The shebang above ensures that this script is executed using Wazuh's embedded Python 3 interpreter,
# which is necessary because Wazuh packages its own isolated Python environment.

import sys      # Used to access command-line arguments passed by Wazuh (specifically the alert file path).
import json     # Used to parse the JSON alert file and to serialize data for Redis.
import redis    # Used to establish a connection to the Redis server and push alerts into the queue.
import os       # Used to read environment variables for configuration.

# ==========================================
# CONFIGURATION BLOCK
# ==========================================
# It is recommended to set these parameters via environment variables.
# However, if the script is executed by a service that lacks the environment context (like the Wazuh agent),
# it will gracefully fall back to the provided default string values.

# The IP address or hostname of the Redis server. Defaults to "192.168.100.39".
REDIS_HOST = os.getenv("REDIS_HOST", "192.168.100.39")
# The port number on which Redis is listening. Defaults to 6379 (standard Redis port).
REDIS_PORT = int(os.getenv("REDIS_PORT", 6379))
# The password for Redis authentication. Defaults to "MyAdmin123".
REDIS_PASSWORD = os.getenv("REDIS_PASSWORD", "MyAdmin123")
# The name of the Redis List (Queue) where raw alerts will be pushed. Defaults to "wazuh_raw_alerts".
QUEUE_NAME = os.getenv("ALERTS_QUEUE", "wazuh_raw_alerts")

# The absolute path to a custom debug log file.
# Note: The 'ossec' user (which Wazuh runs as) MUST have write permissions to this file/directory.
DEBUG_LOG_FILE = "/var/ossec/logs/custom_redis_integration.log"

def log_debug(message):
    """
    Helper function to append debug logs to a specific file on the filesystem.
    This is necessary because standard stdout (print statements) are often discarded
    or ignored when the script is executed natively by the Wazuh integration daemon.
    
    Args:
        message (str): The text message to be written to the log file.
    """
    try:
        # Open the log file in append mode ("a") so we don't overwrite previous logs.
        with open(DEBUG_LOG_FILE, "a", encoding="utf-8") as log_file:
            # Write the message and append a newline character to keep logs organized.
            log_file.write(message + "\n")
    except Exception:
        # If opening or writing to the file fails (e.g., due to insufficient filesystem permissions),
        # we silently catch the exception and pass. We do not want a logging failure to crash the script.
        pass 

def main():
    """
    The main execution function of the integration script.
    Wazuh executes this script by passing the path to a JSON file containing the alert details
    as the first command-line argument.
    """
    # Check if Wazuh actually passed the alert file path argument.
    # sys.argv[0] is the script name itself, sys.argv[1] should be the alert file path.
    if len(sys.argv) < 2:
        log_debug("ERROR: Wazuh did not pass the alert file path (sys.argv[1] is empty).")
        return # Terminate the script gracefully if the file path is missing.

    # Assign the alert file path to a variable for easier access.
    alert_file = sys.argv[1]
    
    try:
        # --- STEP 1: READ THE RAW ALERT ---
        # Open the alert JSON file generated by Wazuh in read-only mode ("r").
        with open(alert_file, 'r', encoding="utf-8") as f:
            # Parse the JSON content of the file into a Python dictionary.
            alert_data = json.load(f)

        # Log a separator and the file path to indicate a new alert is being processed.
        log_debug("--- NEW ALERT TRIGGERED ---")
        log_debug(f"Alert file path: {alert_file}")
        
        # --- STEP 2: CONNECT TO REDIS ---
        # Initialize the Redis client using the configured host, port, and password.
        r = redis.Redis(
            host=REDIS_HOST,
            port=REDIS_PORT,
            # password=REDIS_PASSWORD, # Uncomment this line if Redis requires authentication.
            socket_timeout=5,          # Set a 5-second timeout to prevent the script from hanging indefinitely.
            decode_responses=True      # Automatically decodes returned byte-responses into Python strings.
        )

        # --- STEP 3: PUSH DATA TO REDIS QUEUE ---
        # Serialize the Python dictionary back into a JSON string and push it to the LEFT side of the Redis list.
        # This acts as our message broker queue where the Magister AI pipeline will retrieve it.
        r.lpush(QUEUE_NAME, json.dumps(alert_data))
        
        # Log a success message indicating the integration worked.
        log_debug("SUCCESS: Alert successfully sent to the Redis queue.\n")
        
    except Exception as e:
        # Catch any unexpected errors (e.g., file not found, JSON parsing error, Redis connection timeout).
        # Log the specific error message to help with troubleshooting.
        log_debug(f"INTEGRATION ERROR: {str(e)}\n")

# Standard Python boilerplate to ensure the main() function only runs if the script is executed directly
if __name__ == "__main__":
    main()