version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: redis_brain
    restart: always
    ports:
      # Map host port 6379 to container port 6379
      - "6379:6379"

    volumes:
      # Persist data even if container restarts
      - redis_data:/data


  neo4j:
    image: neo4j:2025.05.0
    container_name: neo4j_memmory
    environment:
        - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always

    volumes:         
       - neo4j_data:/data

volumes:
  neo4j_data:
  redis_data: