"""
Main entry point for running the Magister AI Brain standalone.
This script compiles the LangGraph and executes it to process the current Redis queue.
"""
import time
from src.brain.graph import build_graph
from src.brain.config import r_client

def run_agent():
    """
    Initializes the execution environment, compiles the graph, and triggers a single execution cycle.
    It measures overall performance and safely handles cleanups upon completion or interruption.
    """
    print("=" * 60)
    print("SOC AI:")
    print("=" * 60)

    # Compile the LangGraph. This connects all our nodes (extracting, hunter, skeptic, judge)
    # according to the rules defined in graph.py.
    graph = build_graph()
    total_start_time = time.time()

    try:
        # Initialize an empty state object. This acts as the "blank canvas" that gets passed
        # into the first node (`extracting`). As nodes execute, they will append their data to this dictionary.
        initial_state = {
            "incident": [], 
            "messages": [], 
            "report": "", 
            "escalate": False, 
            "target_ip": "",
            "stix_bundle": "",
            "hunter_report": "",
            "skeptic_report": ""
        }
        
        # Trigger the execution of the graph.
        # recursion_limit=15 prevents infinite loops if a graph's conditional logic is misconfigured.
        final_state = graph.invoke(initial_state, {"recursion_limit": 15})
        
        total_end_time = time.time()
        total_duration = total_end_time - total_start_time

        # Check if the execution generated any messages (meaning it passed extraction and hit the AI agents).
        if final_state.get("messages") and len(final_state["messages"]) > 0:
            last_message = final_state["messages"][-1].content
            
            # If the final message contains "Verdict:", it means the L3 Judge successfully completed its task.
            if "Verdict:" in last_message: 
                print("\n" + "="*70)
                print(">>> OFFICIAL INCIDENT REPORT (L3 JUDGE) <<<".center(70))
                print("="*70)
                # Print the final report generated by the L3 Judge.
                print(last_message)
                print("="*70)

                print(f"\n[SYSTEM] TOTAL PROCESSING TIME: {total_duration:.2f} seconds")
        else:
            # If the state has no messages, it means the `extracting` node returned early without escalating.
            print("\n[SYSTEM] No critical incidents detected in this batch. Graph completed.")
            
    except KeyboardInterrupt:
        # Gracefully handle the user pressing Ctrl+C.
        print("\n[SYSTEM] Shutdown requested by user.")
    except Exception as e:
        # Catch any unexpected Python errors that might occur during execution (e.g., Neo4j crashing, Ollama timing out).
        print(f"\n[CRITICAL ERROR] {e}")
    finally:
        # The finally block ensures that regardless of success, failure, or interruption,
        # we always clean up the testing environment.
        print("\n[SYSTEM] Flushing Redis database to clear deduplication keys and archives...")
        try:
            # flushdb() deletes all keys in the current Redis database.
            # WARNING: This is destructive. In a production environment, you would NOT do this,
            # but for a local standalone test run, it ensures a clean state for the next execution.
            r_client.flushdb()
            print("[SYSTEM] Cleanup successful. Goodbye!")
        except Exception as e:
            print(f"[ERROR] Cleanup failed: {e}")

# Standard Python boilerplate to ensure the code only runs when executed directly.
if __name__ == "__main__":
    run_agent()