"""
Defines the state structure for the LangGraph agent.
This state object is passed from node to node throughout the graph's execution,
allowing different sub-agents to read the results of previous steps and append their own.
"""
from typing_extensions import TypedDict, Annotated
from langgraph.graph.message import add_messages

class IncidentAgentState(TypedDict):
    """
    Expanded state dictionary to isolate individual agent reports.
    By keeping sub-agent reports in separate strings rather than injecting them all into the core message history,
    we prevent LLM instruction confusion (ChatML template collisions) and maintain a clean context window for the final Judge.
    """
    
    # A list representing the raw incident data (currently initialized as empty and unused in the final iteration, 
    # but reserved for raw event objects if needed).
    incident: list 
    
    # The standard LangGraph message history. The `add_messages` reducer ensures that new messages 
    # returned by nodes are appended to this list rather than overwriting it.
    messages: Annotated[list, add_messages]
    
    # A string reserved for an aggregated report, though currently bypassed in favor of individual agent reports.
    report: str
    
    # A boolean flag set by the 'extracting' node. If True, the incident meets the criteria (severity or volume) 
    # to be escalated to the AI agents for deeper analysis.
    escalate: bool     
    
    # A comma-separated string containing all unique IP addresses (internal and external) discovered during the incident.
    # This is passed to Neo4j to pull spatial context.
    target_ip: str 
    
    # A compressed, high-density text summary of the STIX objects generated during the context aggregation phase.
    # Contains the timeline and relationships of the attack.
    stix_bundle: str     
    
    # The raw string output generated by the Hunter (Prosecutor) sub-agent detailing the attack vector.
    hunter_report: str   
    
    # The raw string output generated by the Skeptic (Defender) sub-agent detailing potential benign explanations.
    skeptic_report: str  
