"""
Contains tools and utilities used by the LangGraph agents.
This module bridges the gap between the AI's natural language processing and the deterministic infrastructure data.
"""
import os
from neo4j import GraphDatabase

def check_network_topology(ip_addresses_str: str) -> str:
    """
    Queries the Neo4j Graph Database to determine the infrastructure context of the provided IP addresses.
    It identifies if an IP belongs to a known server, what zone it resides in (e.g., DMZ, Internal), 
    and what services are running on it.
    
    Args:
        ip_addresses_str (str): A comma-separated string of IP addresses extracted by the agent.
        
    Returns:
        str: A formatted block of text detailing the topology for each IP, or stating if it's unknown.
    """
    # Clean and split the incoming string into a list of pure IP addresses.
    # Strips out any accidental quotes, spaces, or newline characters generated by the LLM.
    ips_to_check = [ip.strip(' "\'\n') for ip in ip_addresses_str.split(",") if ip.strip(' "\'\n')]
    
    print("\n" + "-" * 60)
    print(f"[L3-JUDGE -> NEO4J] AI requested topology for IPs: {ips_to_check}")
    
    # Load Neo4j configuration from environment variables.
    # Defaulting to localhost:7687 and standard neo4j/password credentials if not specified in .env.
    URI = os.getenv('NEO4J_URI', "bolt://localhost:7687")
    AUTH = (os.getenv('NEO4J_USER', "neo4j"), os.getenv('NEO4J_PASSWORD', "password"))
    
    # A list to store the textual results for each queried IP.
    combined_results = []
    
    try:
        # Establish a connection to the Neo4j database using the official driver.
        with GraphDatabase.driver(URI, auth=AUTH) as driver:
            # Open a session specific to the 'neo4j' database instance.
            with driver.session(database="neo4j") as session:
                
                # The Cypher query to retrieve server context:
                # 1. MATCH: Finds a Node labeled 'Server' with the exact IP.
                # 2. OPTIONAL MATCH: Looks for 'Service' nodes connected via 'RUNS_ON' relationship.
                # 3. OPTIONAL MATCH: Looks for 'Zone' nodes connected via 'BELONGS_TO' relationship.
                # 4. RETURN: Returns the server name, zone name, and aggregates all service names into a list.
                query = """
                MATCH (s:Server {ip: $ip})
                OPTIONAL MATCH (srv:Service)-[:RUNS_ON]->(s)
                OPTIONAL MATCH (s)-[:BELONGS_TO]->(z:Zone)
                RETURN s.name AS Server, z.name AS Zone, collect(srv.name) AS Services
                """
                
                # Execute the Cypher query sequentially for each IP in the requested list.
                for clean_ip in ips_to_check:
                    # Pass the IP as a parameter ($ip) to prevent Cypher injection vulnerabilities.
                    result = session.run(query, ip=clean_ip)
                    # Fetch the first record from the result set.
                    data = result.single()
                    
                    # If data exists and a Server node was actually found (Server name is not None).
                    if data and data["Server"]:
                        # Format a clean string representing the known topology for this specific IP.
                        result_str = f"IP {clean_ip} -> Server: {data['Server']}, Zone: {data['Zone']}, Services: {', '.join(data['Services'])}"
                        combined_results.append(result_str)
                    else:
                        # If no node matches the IP, it is considered unknown (potentially a rogue actor or external entity).
                        combined_results.append(f"IP {clean_ip} -> No topology data found.")
                        
    except Exception as e:
        # Catch any database connection errors or query syntax errors and return them gracefully.
        # This prevents the entire LangGraph execution from crashing if Neo4j goes down.
        error_msg = f"Neo4j Error: {str(e)}"
        print(f"[NEO4J] CRITICAL ERROR: {error_msg}")
        return error_msg

    # Join the individual results into a single multi-line string that the LLM can easily parse.
    final_output = "\n".join(combined_results)
    print(f"[NEO4J] Returning combined data:\n{final_output}")
    print("-" * 60)
    
    return final_output
